### ISSUE TITLE
Login forbidden

### ISSUE THREAD

**Issue by Kabangi** [dburles/meteor-two-factor#2]
When I create my custom login method I get Login Forbidden while using this package.

What could be the problem?

**Comment by dburles** [comment]
Hey @Kabangi I'm not sure, do you have an example I can take a look at?

**Comment by Kabangi** [comment]
Hi @dburles,

Thank you for taking your time to respond.
Here is a snipper that I added to your example 

'submit [name=signup]'(event, template) {
      event.preventDefault();
      const user = template.$('#user').val();
      const password = template.$('#password').val();
      Accounts.createUser({username:user,password:password},function(error){
         console.log(error);
      });
    }

This code does not log the user in rather it returns login Forbidden

**Comment by Kabangi** [comment]
`if (Meteor.isClient) {
  Template.body.helpers({
    isVerifying() {
      return twoFactor.isVerifying();
    }
  });

  Template.body.events({
    'click #logout'() {
      Meteor.logout();
    }
  });

  Template.login.helpers({
    loginError() {
      return Session.get('loginError');
    }
  });

  Template.login.events({
    'submit form'(event, template) {
      event.preventDefault();

      const user = template.$('#user').val();
      const password = template.$('#password').val();

      twoFactor.getAuthCode(user, password, error => {
        if (error) {
          return Session.set('loginError', error.reason);
        }

        Session.set('loginError', '');
      });
    }
  });

  Template.signup.helpers({
    loginError() {
      return Session.get('loginError');
    }
  });

  Template.signup.events({
    'submit [name=signup]'(event, template) {
      event.preventDefault();

      const user = template.$('#user').val();
      const password = template.$('#password').val();
      Accounts.createUser({username:user,password:password},function(error){
         console.log(error);
      });

    }
  });

  Template.verify.helpers({
    verifyError() {
      return Session.get('verifyError');
    }
  });

  Template.verify.events({
    'submit form'(event, template) {
      event.preventDefault();

      const code = template.$('#code').val();

      twoFactor.verifyAndLogin(code, error => {
        if (error) {
          return Session.set('verifyError', error.reason);
        }

        Session.set('verifyError', '');
      });
    }
  });
} else {
  twoFactor.sendCode = (user, code) => {
    console.log(`Authentication code for '${user.username}' user is: ${code}`);
  };

  // Gives us an account to test with
  Meteor.startup(() => {
    if (Meteor.users.find().count() === 0) {
      Accounts.createUser({
        username: 'example',
        password: 'password'
      });
    }
  });
}`

**Comment by Kabangi** [comment]
if (Meteor.isClient) {
  Template.body.helpers({
    isVerifying() {
      return twoFactor.isVerifying();
    }
  });
  Template.body.events({
    'click #logout'() {
      Meteor.logout();
    }
  });

  Template.login.helpers({
    loginError() {
      return Session.get('loginError');
    }
  });

  Template.login.events({
    'submit form'(event, template) {
      event.preventDefault();

      const user = template.$('#user').val();
      const password = template.$('#password').val();

      twoFactor.getAuthCode(user, password, error => {
        if (error) {
          return Session.set('loginError', error.reason);
        }

        Session.set('loginError', '');
      });
    }
  });

  Template.signup.helpers({
    loginError() {
      return Session.get('loginError');
    }
  });

  Template.signup.events({
    'submit [name=signup]'(event, template) {
      event.preventDefault();

      const user = template.$('#user').val();
      const password = template.$('#password').val();
      Accounts.createUser({username:user,password:password},function(error){
         console.log(error);
      });

    }
  });

  Template.verify.helpers({
    verifyError() {
      return Session.get('verifyError');
    }
  });

  Template.verify.events({
    'submit form'(event, template) {
      event.preventDefault();

      const code = template.$('#code').val();

      twoFactor.verifyAndLogin(code, error => {
        if (error) {
          return Session.set('verifyError', error.reason);
        }

        Session.set('verifyError', '');
      });
    }
  });
} else {
  twoFactor.sendCode = (user, code) => {
    console.log(`Authentication code for '${user.username}' user is: ${code}`);
  };

  // Gives us an account to test with
  Meteor.startup(() => {
    if (Meteor.users.find().count() === 0) {
      Accounts.createUser({
        username: 'example',
        password: 'password'
      });
    }
  });
}

**Comment by dburles** [comment]
Thanks @Kabangi update to 1.0.3 for the fix

**Comment by Kabangi** [comment]
Thanks for the fix, but reset password also raises the same issue

**Comment by dburles** [comment]
oh lol thanks I'll fix that

**Comment by dburles** [comment]
@Kabangi just release 1.0.4, let me know if you have any other problems
