### ISSUE TITLE
Use as well the default meteor loginWithPassword

### ISSUE THREAD

**Issue by EmanueleGuidotti** [dburles/meteor-two-factor#20]
Hi, thanks for the great works you have done making this package.
I'd like to know if is possible to use the default `Meteor.loginWithPassword` in conjunction while using this package whitin a project. Actually when I try to create two different login sections, one using two-factor and one using the default Meteor login, I get a `login forbidden` error using `Meteor.loginWithPassword`.

**Comment by dburles** [comment]
Hey thanks Emanuele, what you're looking for is the `validateLoginAttempt` method: https://github.com/dburles/meteor-two-factor#validateloginattempt-optional. See here for an example https://github.com/dburles/meteor-two-factor#usage-server

**Comment by EmanueleGuidotti** [comment]
It works as expected. Thank you for your help!
