### ISSUE TITLE
twoFactor.validateLoginAttempt not firing

### ISSUE THREAD

**Issue by aarlaud** [dburles/meteor-two-factor#4]
Hello,

My app has 2 account types allowed:
- Google OAuth based for specific domains
- Password based where 2FA is enabled with your package.

I am trying to put some logic in validateLoginAttempt which doesn't seem to be firing based except if it is resume login attempt. Am I doing something wrong?
It also seems that Accounts.onLogin callback does not fire at all for accounts through 2FA. Is that expected?

Please let me know.

thanks !

Great stuff otherwise, thanks for putting this together !
Antoine

**Comment by dburles** [comment]
It should run! not too sure what's going wrong. The code isn't too complicated if you wanted to have a look into it. https://github.com/dburles/meteor-two-factor/blob/master/server.js#L100-L113

**Comment by aarlaud** [comment]
Hi, I finally got time to dig into this. After turning this in many different directions, I think I got it.
Not sure how it ended up being that way, but the call to _loginUser does not seem to fire validateLoginAttempt. I copied your code over and changed _loginUser by _attemptLogin and then it goes through validateLoginAttempt. Looks like attemptLogin runs the validateLoginAttempt and loginUser does not.
"Reading"(1am spotting) across accounts-base, it looks like two distinct processes, but _attemptLogin seems called by default for external service like Google, hence the behavior i was seeing (working properly for non 2FA attempts).
I resolved my problem but was wondering if something maybe changed in accounts-base since your last release maybe? I'll review the release notes to see if there was a change. Or there might be something else going on that I still haven't identified....

**Comment by dburles** [comment]
Thanks for the insight! Would you mind putting together a minimal reproduction app? http://stackoverflow.com/help/mcve. It would be super helpful for me to take a look into things.

**Comment by aarlaud** [comment]
I created a repo => https://github.com/aarlaud/two-factor-loginattempt-issue-MCV
I took your example app and added the loginattempt code in the server code.
Normal Login doesn't fire it. Refreshing while logged in does work as the login type is resume.

My solution consists in changing _loginUser by _attemptLogin in the verifyCodeAndLogin method code on server side:
```
  'twoFactor.verifyCodeAndLogin'(options) {
<.....>
    Meteor.users.update(user._id, {
      $unset: {
        [fieldName]: ''
      }
    });
// I put a custom type, clearer than the unknown type accounts-base provides otherwise
    var result = {type: '2FALogin', userId: user._id};
    return Accounts._attemptLogin(this, 'login', '', result);
  }
});
```

Where I looked to find this => https://github.com/meteor/accounts/blob/master/packages/accounts-base/accounts_server.js line 298.

Hope it helps. Let me know if I messed something up on my side or not setting things up the right way.
Antoine

**Comment by dburles** [comment]
Thanks, that's great @aarlaud I'll look into it

**Comment by dburles** [comment]
Thanks @aarlaud I've just released `1.1.2` with this fix

**Comment by partus** [comment]
Seems like this fix is not actually a complete fix. In my case I had problems with verifying the code with exception "Login Forbidden", which as I found comes from `Accounts._attemptLogin`.

after changing it to `Accounts._loginUser` as it was in previous version it works fine.

**Comment by dburles** [comment]
Yeah sorry @partus it's still broken, see #7 I haven't had time to work on it but would very much appreciate a pull request

**Comment by dburles** [comment]
Also what version of Meteor were you using?
