### ISSUE TITLE
twoFactorVerifyCodeAndLogin AND aldeed:collection2-core Compatibility

### ISSUE THREAD

**Issue by Ontokrat** [dburles/meteor-two-factor#5]
Hi David ,

First, thank you for your job, your 2FA plugin works great !
Since two days ago, I tried to implement the aldeed:collection2-core plugin (pretty mainstream in meteor dev...). Here's my issue : 

The creation of a user works & the new schema is attached to the user.
But I'm unable to log in my account: the first _login step_ works great, I receive the code, but the _verify step_ give me a 403 error 
`Error: Invalid code [403]
    at [object Object].twoFactorVerifyCodeAndLogin (packages/dburles:two-factor/server.js:87:13)`
So this line is:
```
      if (options.code !== user[fieldName]) {                                                                // 86
        throw new Meteor.Error(403, "Invalid code");                                                         // 87
      }                                                                                                                            // 88

```

At the end of my user schema, if I comment the last line 
`Meteor.users.attachSchema(Schema.User);`
everything is back to normal - like a charm. But obviously, the new user schema is not attached to the user...

Any idea of what is going on ? 
Help me Obi Wan Kanobi.

-----------------------
In details, in the Method _twoFactor.verifyCodeAndLogin_ : 

- At start: 
```
userId : null
params : [{"user":{"email":"my@adress.com"},"password":"passpass","code":"234926"}]

```
- the find on users return:
```
coll : users
func : find
selector : {"emails.address":"my@adress.com"}
```

-the fetch on users return:
```
coll : users
selector : {"emails.address":"my@adress.com"}
func : fetch
cursor : true
limit : 1
docsFetched : 1
docSize : 516
```
- then the error:
```
message: Invalid code [403] 
stack:
Error: Invalid code [403]
    at [object Object].twoFactorVerifyCodeAndLogin (packages/dburles:two-factor/server.js:87:13)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    at packages/meteorhacks_kadira.js:2619:38
```

**Comment by dburles** [comment]
Hey @Ontokrat nicely written, I think all that's required is to add `twoFactorCode` to your user schema. Let me know if that fixes it. To be specific, validate a 6 digit `Number`.

You can also customise this field name if you prefer: https://github.com/dburles/meteor-two-factor#options

**Comment by Ontokrat** [comment]
It works! Just to be clear for anyone else:
```
twoFactorCode: {
        type: String,
        optional: true
    },
```

Thanks a lot @dburles for taking time for me.

**Comment by dburles** [comment]
@Ontokrat hmm should definitely be `Number` rather than `String`

**Comment by Ontokrat** [comment]
@dburles `Number` doesn't work, even with `regEx: /^[0-9]{6}$/`
Do you prefer `Number` over `String` for security reasons?
Is this code looks better to you (tested - works fine)?
```
twoFactorCode: {
        type: String,
        regEx: /^[0-9]{6}$/,
        optional: true
    },
```

**Comment by dburles** [comment]
oh sorry, you're right, it is a String. Been a while since I've looked at the source! Yep that code looks good!
