### ISSUE TITLE
suggestion: allow canceling login process

### ISSUE THREAD

**Issue by vbelolapotkov** [dburles/meteor-two-factor#8]
Add client API method for canceling verification process: 
IMO it has to do two things:
1. clear twoFactorCode value in the user doc (on the server)
2. reset isVerifying state

This will allow new login attempt with another account.

can create PR if help needed

**Comment by dburles** [comment]
That sounds like a good idea, I'd definitely appreciate a PR.

**Comment by dburles** [comment]
Thanks @vbelolapotkov released as 1.2.0. I'm looking for maintainers if you're interested.

**Comment by vbelolapotkov** [comment]
@dburles thanks for asking. I never did this before but I can try on best effort basis if it's ok for you
